### ISSUE TITLE
How to catch Fcm*Exception when calling FcmClient.send()?

### ISSUE THREAD

**Issue by ben512** [bytefish/FcmJava#20]
When calling FcmClient.send(), I can only catch RuntimeException, how do I catch the more specific FCM exceptions like FcmAuthenticationException, FcmBadRequestException, FcmRetryAfterException, FcmGeneralException, etc?

Thanks!

**Comment by bytefish** [comment]
You are totally right. Yes, all Exceptions got wrapped in a ``RuntimeException``. I am quite ashamed, that I did classic Pokémon Exception Handling (catch them all!) in the Client. I have fixed the issue and will release a new version. This ticket will be updated.

**Comment by bytefish** [comment]
I have pushed FcmJava Version 1.2 to the Maven Central Repository, which contains the above bugfix. It should be available in some hours. You should now be able to catch all of the mentioned exceptions! 👍

**Comment by ben512** [comment]
Thanks for the update, but the fix does not seem to work, I still can't catch FcmException, only RuntimeException.

Looks like the FcmException is not being propagated from StatusResponseInterceptor?

**Comment by bytefish** [comment]
Really? I have added an Integration Test at:

* https://github.com/bytefish/FcmJava/blob/master/FcmJava/fcmjava-client/src/test/java/de/bytefish/fcmjava/client/tests/integration/FcmClientIntegrationTest.java#L86

It shows how to catch an FcmAuthenticationException for example.

**Comment by bytefish** [comment]
I have reworked some parts and released Version 2.0. You should now be able to catch the Exceptions, I added some Integration Tests provoking the Exceptions.

Integration Test for Bad Request:

* https://github.com/bytefish/FcmJava/blob/master/FcmJava/fcmjava-client/src/test/java/de/bytefish/fcmjava/client/tests/integration/FcmClientIntegrationTest.java#L96

Integration Test for Authentication:

* https://github.com/bytefish/FcmJava/blob/master/FcmJava/fcmjava-client/src/test/java/de/bytefish/fcmjava/client/tests/integration/FcmClientIntegrationTest.java#L124

**Comment by ben512** [comment]
Thanks for the update.

I tried out your test but it does not appear to work for me, I can still just catch the RuntimeException.

However I was able to get the FcmException by doing the following:

`
try {
    FcmClient.send(...);
} catch (RuntimeException ex) {
    FcmException fcmEx = (FcmException)ex.getCause();
    if (fcmEx instanceof FcmAuthenticationException) {
       // handle exception
    }
}
`
Could you check again?

**Comment by bytefish** [comment]
You need to update your dependencies to version ``2.0``. Then it should work.

**Comment by ben512** [comment]
I realized I only updated fcm-core but did not update fcm-client.

All is good now, thanks!

**Comment by bytefish** [comment]
Great! :+1: Thanks for the Feedback.
